### ISSUE TITLE
bad image in stac?

### ISSUE THREAD

**Issue by mukhery** [microsoft/PlanetaryComputerExamples#22]
Received this error during some batch processing, so maybe this image in particular is corrupt?
```
RasterioIOError: '/vsicurl/https://sentinel2l2a01.blob.core.windows.net/sentinel2-l2/17/Q/LA/2017/12/27/S2B_MSIL2A_20171227T160459_N0212_R054_T17QLA_20201014T165101.SAFE/GRANULE/L2A_T17QLA_A004227_20171227T160750/IMG_DATA/R10m/T17QLA_20171227T160459_B04_10m.tif<url_shortened>' not recognized as a supported file format.
```
Accessed via this stac:
`"https://planetarycomputer-staging.microsoft.com/api/stac/v1/"`

**Comment by TomAugspurger** [comment]
Thanks @mukhery, we're reprocessing some sentinel items, and I wonder if this file was replaced by a newer one. I did not see an object at this URL in the storage container (corrupt or otherwise).

cc @lossyrob. https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2B_MSIL2A_20171227T160459_N0212_R054_T17QLA_20201014T165101.SAFE is the URL in our STAC endpoint.

**Comment by lossyrob** [comment]
This does look like a case of reprocessing. I'll check with the folks doing data processing for us and see why this was reprocessed - this could potentially be an issue for a wider range of STAC Items.

**Comment by mukhery** [comment]
Thanks @TomAugspurger and @lossyrob! We have seen the issue with other items, but it does seem to be rare.

**Comment by TomAugspurger** [comment]
As mentioned in our [changelog](https://planetarycomputer.microsoft.com/docs/overview/changelog/#changes-to-existing-datasets), we think we've fixed up all these issues. Let us know if you spot any more.
